version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "15432:5432"
  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres