version: "3"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "15432:5432"
  db-migration:
    build:
      context: .
      dockerfile: DockerfileFlyway
    depends_on:
      - postgres
    restart: no
    environment:
      FLYWAY_URL:
      FLYWAY_USER:
      FLYWAY_PASSWORD:
  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db-migration
      - postgres
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres